FROM python:3.13
WORKDIR /app
RUN pip install uv
COPY pyproject.toml ./
COPY uv.lock ./
RUN uv sync --no-cache
ENV PATH="/app/.venv/bin:$PATH"
COPY . .
EXPOSE 8501
CMD ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]